version: '2'
services:
  todo-web:
    build: todo.web
    ports:
        - "5000:80"
    depends_on:
        - todo-postgres
    environment:
        - ConnectionStrings__PostgresConnection=Server=postgres; Port=5432; User Id=myuser; Password=none; Database=todo
  todo-postgres:
    image: "postgres"
    container_name: "postgres"
    volumes:
        - ../data:/var/lib/postgresql/data/pgdata
    environment:
        - POSTGRES_USER=myuser
        - POSTGRES_PASSWORD=none
        - POSTGRES_DB=todo
        - PGDATA=/var/lib/postgresql/data/pgdata
  todo-health:
    build: todo.health
    depends_on:
        - todo-web
    environment:
        - Health__Url=http://todo-web:80/health